# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_portvalg(object):
    def setupUi(self, portvalg):
        portvalg.setObjectName(_fromUtf8("portvalg"))
        portvalg.resize(464, 636)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(portvalg.sizePolicy().hasHeightForWidth())
        portvalg.setSizePolicy(sizePolicy)
        portvalg.setMaximumSize(QtCore.QSize(464, 636))
        self.horizontalLayout = QtGui.QHBoxLayout(portvalg)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.port1Label = QtGui.QLabel(portvalg)
        self.port1Label.setObjectName(_fromUtf8("port1Label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.port1Label)
        self.port1LineEdit = QtGui.QLineEdit(portvalg)
        self.port1LineEdit.setObjectName(_fromUtf8("port1LineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.port1LineEdit)
        self.port2Label = QtGui.QLabel(portvalg)
        self.port2Label.setObjectName(_fromUtf8("port2Label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.port2Label)
        self.port2LineEdit = QtGui.QLineEdit(portvalg)
        self.port2LineEdit.setObjectName(_fromUtf8("port2LineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.port2LineEdit)
        self.port3Label = QtGui.QLabel(portvalg)
        self.port3Label.setObjectName(_fromUtf8("port3Label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.port3Label)
        self.port3LineEdit = QtGui.QLineEdit(portvalg)
        self.port3LineEdit.setObjectName(_fromUtf8("port3LineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.port3LineEdit)
        self.port4Label = QtGui.QLabel(portvalg)
        self.port4Label.setObjectName(_fromUtf8("port4Label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.port4Label)
        self.port4LineEdit = QtGui.QLineEdit(portvalg)
        self.port4LineEdit.setObjectName(_fromUtf8("port4LineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.port4LineEdit)
        self.port5Label = QtGui.QLabel(portvalg)
        self.port5Label.setObjectName(_fromUtf8("port5Label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.port5Label)
        self.port5LineEdit = QtGui.QLineEdit(portvalg)
        self.port5LineEdit.setObjectName(_fromUtf8("port5LineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.port5LineEdit)
        self.port6Label = QtGui.QLabel(portvalg)
        self.port6Label.setObjectName(_fromUtf8("port6Label"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.port6Label)
        self.port6LineEdit = QtGui.QLineEdit(portvalg)
        self.port6LineEdit.setObjectName(_fromUtf8("port6LineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.port6LineEdit)
        self.port7Label = QtGui.QLabel(portvalg)
        self.port7Label.setObjectName(_fromUtf8("port7Label"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.port7Label)
        self.port7LineEdit = QtGui.QLineEdit(portvalg)
        self.port7LineEdit.setObjectName(_fromUtf8("port7LineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.port7LineEdit)
        self.port8Label = QtGui.QLabel(portvalg)
        self.port8Label.setObjectName(_fromUtf8("port8Label"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.port8Label)
        self.port8LineEdit = QtGui.QLineEdit(portvalg)
        self.port8LineEdit.setObjectName(_fromUtf8("port8LineEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.port8LineEdit)
        self.port9Label = QtGui.QLabel(portvalg)
        self.port9Label.setObjectName(_fromUtf8("port9Label"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.port9Label)
        self.port9LineEdit = QtGui.QLineEdit(portvalg)
        self.port9LineEdit.setObjectName(_fromUtf8("port9LineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.port9LineEdit)
        self.port10Label = QtGui.QLabel(portvalg)
        self.port10Label.setObjectName(_fromUtf8("port10Label"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.port10Label)
        self.port10LineEdit = QtGui.QLineEdit(portvalg)
        self.port10LineEdit.setObjectName(_fromUtf8("port10LineEdit"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.port10LineEdit)
        self.port11Label = QtGui.QLabel(portvalg)
        self.port11Label.setObjectName(_fromUtf8("port11Label"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.port11Label)
        self.port11LineEdit = QtGui.QLineEdit(portvalg)
        self.port11LineEdit.setObjectName(_fromUtf8("port11LineEdit"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.port11LineEdit)
        self.port12Label = QtGui.QLabel(portvalg)
        self.port12Label.setObjectName(_fromUtf8("port12Label"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.port12Label)
        self.port12LineEdit = QtGui.QLineEdit(portvalg)
        self.port12LineEdit.setObjectName(_fromUtf8("port12LineEdit"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.port12LineEdit)
        self.port13Label = QtGui.QLabel(portvalg)
        self.port13Label.setObjectName(_fromUtf8("port13Label"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.port13Label)
        self.port13LineEdit = QtGui.QLineEdit(portvalg)
        self.port13LineEdit.setObjectName(_fromUtf8("port13LineEdit"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.port13LineEdit)
        self.port14Label = QtGui.QLabel(portvalg)
        self.port14Label.setObjectName(_fromUtf8("port14Label"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.port14Label)
        self.port14LineEdit = QtGui.QLineEdit(portvalg)
        self.port14LineEdit.setObjectName(_fromUtf8("port14LineEdit"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.port14LineEdit)
        self.port15Label = QtGui.QLabel(portvalg)
        self.port15Label.setObjectName(_fromUtf8("port15Label"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.port15Label)
        self.port15LineEdit = QtGui.QLineEdit(portvalg)
        self.port15LineEdit.setObjectName(_fromUtf8("port15LineEdit"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.port15LineEdit)
        self.port16Label = QtGui.QLabel(portvalg)
        self.port16Label.setObjectName(_fromUtf8("port16Label"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.port16Label)
        self.port16LineEdit = QtGui.QLineEdit(portvalg)
        self.port16LineEdit.setObjectName(_fromUtf8("port16LineEdit"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.port16LineEdit)
        self.port17Label = QtGui.QLabel(portvalg)
        self.port17Label.setObjectName(_fromUtf8("port17Label"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.port17Label)
        self.port17LineEdit = QtGui.QLineEdit(portvalg)
        self.port17LineEdit.setObjectName(_fromUtf8("port17LineEdit"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.port17LineEdit)
        self.port18Label = QtGui.QLabel(portvalg)
        self.port18Label.setObjectName(_fromUtf8("port18Label"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.port18Label)
        self.port18LineEdit = QtGui.QLineEdit(portvalg)
        self.port18LineEdit.setObjectName(_fromUtf8("port18LineEdit"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.FieldRole, self.port18LineEdit)
        self.port19Label = QtGui.QLabel(portvalg)
        self.port19Label.setObjectName(_fromUtf8("port19Label"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.LabelRole, self.port19Label)
        self.port19LineEdit = QtGui.QLineEdit(portvalg)
        self.port19LineEdit.setObjectName(_fromUtf8("port19LineEdit"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.port19LineEdit)
        self.port20Label = QtGui.QLabel(portvalg)
        self.port20Label.setObjectName(_fromUtf8("port20Label"))
        self.formLayout.setWidget(19, QtGui.QFormLayout.LabelRole, self.port20Label)
        self.port20LineEdit = QtGui.QLineEdit(portvalg)
        self.port20LineEdit.setObjectName(_fromUtf8("port20LineEdit"))
        self.formLayout.setWidget(19, QtGui.QFormLayout.FieldRole, self.port20LineEdit)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.enhedensIPLabel = QtGui.QLabel(portvalg)
        self.enhedensIPLabel.setObjectName(_fromUtf8("enhedensIPLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.enhedensIPLabel)
        self.enhedensIPLineEdit = QtGui.QLineEdit(portvalg)
        self.enhedensIPLineEdit.setObjectName(_fromUtf8("enhedensIPLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.enhedensIPLineEdit)
        self.navnPTjenesteLabel = QtGui.QLabel(portvalg)
        self.navnPTjenesteLabel.setObjectName(_fromUtf8("navnPTjenesteLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.navnPTjenesteLabel)
        self.navnPTjenesteLineEdit = QtGui.QLineEdit(portvalg)
        self.navnPTjenesteLineEdit.setObjectName(_fromUtf8("navnPTjenesteLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.navnPTjenesteLineEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.pushButton = QtGui.QPushButton(portvalg)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(portvalg)
        QtCore.QMetaObject.connectSlotsByName(portvalg)

    def retranslateUi(self, portvalg):
        portvalg.setWindowTitle(_translate("portvalg", "Form", None))
        self.port1Label.setText(_translate("portvalg", "Port 1", None))
        self.port2Label.setText(_translate("portvalg", "Port 2", None))
        self.port3Label.setText(_translate("portvalg", "Port 3", None))
        self.port4Label.setText(_translate("portvalg", "Port 4", None))
        self.port5Label.setText(_translate("portvalg", "Port 5", None))
        self.port6Label.setText(_translate("portvalg", "Port 6", None))
        self.port7Label.setText(_translate("portvalg", "Port 7", None))
        self.port8Label.setText(_translate("portvalg", "Port 8", None))
        self.port9Label.setText(_translate("portvalg", "Port 9", None))
        self.port10Label.setText(_translate("portvalg", "Port 10", None))
        self.port11Label.setText(_translate("portvalg", "Port 11", None))
        self.port12Label.setText(_translate("portvalg", "Port 12", None))
        self.port13Label.setText(_translate("portvalg", "Port 13", None))
        self.port14Label.setText(_translate("portvalg", "Port 14", None))
        self.port15Label.setText(_translate("portvalg", "Port 15", None))
        self.port16Label.setText(_translate("portvalg", "Port 16", None))
        self.port17Label.setText(_translate("portvalg", "Port 17", None))
        self.port18Label.setText(_translate("portvalg", "Port 18", None))
        self.port19Label.setText(_translate("portvalg", "Port 19", None))
        self.port20Label.setText(_translate("portvalg", "Port 20", None))
        self.enhedensIPLabel.setText(_translate("portvalg", "Enhedens IP", None))
        self.navnPTjenesteLabel.setText(_translate("portvalg", "Navn på Tjeneste", None))
        self.pushButton.setText(_translate("portvalg", "Sæt Porte", None))

